export enum SchemaType {
  And = '__!quartet/And!__',
  Array = '__!quartet/Array!__',
  ArrayOf = '__!quartet/ArrayOf!__',
  Boolean = '__!quartet/Boolean!__',
  Finite = '__!quartet/Finite!__',
  Function = '__!quartet/Function!__',
  Max = '__!quartet/Max!__',
  MaxLength = '__!quartet/MaxLength!__',
  Min = '__!quartet/Min!__',
  MinLength = '__!quartet/MinLength!__',
  Negative = '__!quartet/Negative!__',
  Not = '__!quartet/Not!__',
  Number = '__!quartet/Number!__',
  Object = '__!quartet/Object!__',
  Pair = '__!quartet/Pair!__',
  Positive = '__!quartet/Positive!__',
  SafeInteger = '__!quartet/SafeInteger!__',
  String = '__!quartet/String!__',
  Symbol = '__!quartet/Symbol!__',
  Test = '__!quartet/Test!__',
  Variant = '__!quartet/Variant!__',
  Custom = '__!quartet/Custom!__',
}
