export enum ValidatorType {
  And = "And",
  Array = "Array",
  ArrayOf = "ArrayOf",
  Boolean = "Boolean",
  Constant = "Constant",
  DictionaryOf = "DictionaryOf",
  Enum = "Enum",
  In = "In",
  Finite = "Finite",
  Function = "Function",
  Max = "Max",
  Min = "Min",
  Negative = "Negative",
  NonNegative = "NonNegative",
  NonPositive = "NonPositive",
  Not = "Not",
  Number = "Number",
  Object = "Object",
  Positive = "Positive",
  SafeInteger = "SafeInteger",
  String = "String",
  Test = "Test",
  Variant = "Variant"
}
